#!/bin/bash
make clean && make fast
echo CSR DD NOT
./EulerEquations2D 0_Parameters/CSR/DD/NOT.dat >> CSR_DD_NOT.txt
echo CSR DD ILU
./EulerEquations2D 0_Parameters/CSR/DD/ILU.dat >> CSR_DD_ILU.txt
echo CSR DD DIAG
./EulerEquations2D 0_Parameters/CSR/DD/DIAG.dat >> CSR_DD_DIAG.txt
################################################################################
echo CSR SUPG NOT
./EulerEquations2D 0_Parameters/CSR/SUPG/NOT.dat >> CSR_SUPG_NOT.txt
echo CSR SUPG ILU
./EulerEquations2D 0_Parameters/CSR/SUPG/ILU.dat >> CSR_SUPG_ILU.txt
echo CSR SUPG DIAG
./EulerEquations2D 0_Parameters/CSR/SUPG/DIAG.dat >> CSR_SUPG_DIAG.txt
################################################################################
echo EBE DD NOT
./EulerEquations2D 0_Parameters/EBE/DD/NOT.dat >> EBE_DD_NOT.txt
echo EBE DD BLOCKDIAG
./EulerEquations2D 0_Parameters/EBE/DD/BLOCKDIAG.dat >> EBE_DD_BLOCKDIAG.txt
echo EBE DD DIAG
./EulerEquations2D 0_Parameters/EBE/DD/DIAG.dat >> EBE_DD_DIAG.txt
echo EBE DD BLOCKJACOBI
./EulerEquations2D 0_Parameters/EBE/DD/BLOCKJACOBI.dat >> EBE_DD_BLOCKJACOBI.txt
echo EBE DD JACOBI
./EulerEquations2D 0_Parameters/EBE/DD/JACOBI.dat >> EBE_DD_JACOBI.txt
echo EBE DD SORBLOCK05
./EulerEquations2D 0_Parameters/EBE/DD/SORBLOCK05.dat >> EBE_DD_SORBLOCK05.txt
echo EBE DD SOR05
./EulerEquations2D 0_Parameters/EBE/DD/SOR05.dat >> EBE_DD_SOR05.txt
echo EBE DD SORBLOCK10
./EulerEquations2D 0_Parameters/EBE/DD/SORBLOCK10.dat >> EBE_DD_SORBLOCK10.txt
echo EBE DD SOR10
./EulerEquations2D 0_Parameters/EBE/DD/SOR10.dat >> EBE_DD_SOR10.txt
echo EBE DD SORBLOCK15
./EulerEquations2D 0_Parameters/EBE/DD/SORBLOCK15.dat >> EBE_DD_SORBLOCK15.txt
echo EBE DD SOR15
./EulerEquations2D 0_Parameters/EBE/DD/SOR15.dat >> EBE_DD_SOR15.txt
################################################################################
echo EBE SUPG NOT
./EulerEquations2D 0_Parameters/EBE/SUPG/NOT.dat >> EBE_SUPG_NOT.txt
echo EBE SUPG BLOCKDIAG
./EulerEquations2D 0_Parameters/EBE/SUPG/BLOCKDIAG.dat >> EBE_SUPG_BLOCKDIAG.txt
echo EBE SUPG DIAG
./EulerEquations2D 0_Parameters/EBE/SUPG/DIAG.dat >> EBE_SUPG_DIAG.txt
echo EBE SUPG BLOCKJACOBI
./EulerEquations2D 0_Parameters/EBE/SUPG/BLOCKJACOBI.dat >> EBE_SUPG_BLOCKJACOBI.txt
echo EBE SUPG JACOBI
./EulerEquations2D 0_Parameters/EBE/SUPG/JACOBI.dat >> EBE_SUPG_JACOBI.txt
echo EBE SUPG SORBLOCK05
./EulerEquations2D 0_Parameters/EBE/SUPG/SORBLOCK05.dat >> EBE_SUPG_SORBLOCK05.txt
echo EBE SUPG SOR05
./EulerEquations2D 0_Parameters/EBE/SUPG/SOR05.dat >> EBE_SUPG_SOR05.txt
echo EBE SUPG SORBLOCK10
./EulerEquations2D 0_Parameters/EBE/SUPG/SORBLOCK10.dat >> EBE_SUPG_SORBLOCK10.txt
echo EBE SUPG SOR10
./EulerEquations2D 0_Parameters/EBE/SUPG/SOR10.dat >> EBE_SUPG_SOR10.txt
echo EBE SUPG SORBLOCK15
./EulerEquations2D 0_Parameters/EBE/SUPG/SORBLOCK15.dat >> EBE_SUPG_SORBLOCK15.txt
echo EBE SUPG SOR15
./EulerEquations2D 0_Parameters/EBE/SUPG/SOR15.dat >> EBE_SUPG_SOR15.txt
